baseURL = "https://life.tlanyan.me"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
author = "tlanyan"
title = "我的一生"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Copyright [tlanyan](https://tlanyan.me) | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["tlanyan","hugo","日志","我的一生"]

	# Add meta description in head part
	description = "平凡的世界，喜怒哀乐"

	# Add pagetitle to homepage <title> tag
	pagetitle = "tlanyan"

	# Add a subtitle to your website
	subtitle = "这里记录每一天"

	# Activate to show authors on pages if available
	#listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "/img/vitae.jpg"

	# Optional favicons for website
	favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["posts"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["posts"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = false

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
#shortname = "" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "主页"
url = "/"
weight = 1

[[menu.main]]
name = "所有文章"
url = "/posts"
weight = 2

[[menu.main]]
name = "关于"
url = "/about"
weight = 3

[[menu.main]]
name = "标签"
url = "/tags"
weight = 4

[[menu.main]]
name = "分类"
url = "/categories"
weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/tlanyan/netlify"

#[[params.social]]
#name = "Email"
#icon = "fas fa-envelope"
#cmd = "mailto:example@example.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
